version: '3'

services:
  front:
    image: ippolab/athena-frontend
    container_name: athena_front
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-frontend"
      - "traefik.frontend.rule=Host:athena.${HOSTNAME}"
      - "traefik.port=80"
    networks:
      - web
  web:
    image: ippolab/athena-backend
    container_name: athena_back
    restart: always
    depends_on:
      - db
      - redis
      - rabbit
    env_file:
      - .env
    volumes:
      - ./media:/media
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-backend"
      - "traefik.frontend.rule=Host:api.athena.${HOSTNAME}"
      - "traefik.port=8000"
    networks:
      - web
  celery:
    image: ippolab/athena-backend
    container_name: athena_celery
    restart: always
    depends_on:
      - db
      - redis
      - rabbit
    env_file:
      - .env
    command: celery worker -A athena --concurrency=4
    labels:
      - "traefik.enable=true"
    networks:
      - web
  celery-beat:
    image: ippolab/athena-backend
    container_name: athena_celery_beat
    restart: always
    depends_on:
      - db
      - redis
      - rabbit
    env_file:
      - .env
    command: celery beat -A athena
    labels:
      - "traefik.enable=true"
    networks:
      - web
  db:
    image: postgres:11.2-alpine
    container_name: athena_pgdb
    restart: always
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
    networks:
      - web
  redis:
    image: redis:5.0.3-alpine
    container_name: athena_redis
    restart: always
    labels:
      - "traefik.enable=true"
    networks:
      - web
  rabbit:
    image: rabbitmq:3.7.13-management-alpine
    container_name: athena_rabbitmq
    hostname: rabbitmq
    restart: always
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-rabbit"
      - "traefik.frontend.rule=Host:rabbit.athena.${HOSTNAME}"
      - "traefik.port=15672"
    networks:
      - web
  flower:
    image: mher/flower
    container_name: athena_flower
    restart: always
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-flower"
      - "traefik.frontend.rule=Host:flower.athena.${HOSTNAME}"
      - "traefik.frontend.auth.basic=${ADMIN_USERNAME}:${ADMIN_PASSWORD}"
      - "traefik.port=8888"
    networks:
      - web

networks:
  web:
    external: true
