version: '3'

services:
  front:
    image: ippolab/athena-frontend
    container_name: athena_front
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-frontend"
      - "traefik.frontend.rule=Host:athena.${HOSTNAME}"
      - "traefik.port=80"
    networks:
      - web
  nginx:
    image: nginx:1.15.9-alpine
    container_name: athena_nginx
    restart: unless-stopped
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-nginx"
      - "traefik.frontend.rule=Host:api.athena.${HOSTNAME};PathPrefix:/static,PathPrefix:/media"
      - "traefik.port=80"
    networks:
      - web
  back:
    image: ippolab/athena-backend
    container_name: athena_back
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-backend"
      - "traefik.frontend.rule=Host:api.athena.${HOSTNAME}"
      - "traefik.port=8000"
    networks:
      - web
  db:
    image: postgres:11.2-alpine
    container_name: athena_postgre
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-postgre"
      - "traefik.frontend.rule=Host:"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - web
  pgadmin:
    image: dpage/pgadmin4:4.6
    container_name: athena_pgadmin
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-pgadmin"
      - "traefik.frontend.rule=Host:pgadmin.athena.${HOSTNAME}"
      - "traefik.port=80"
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - web

networks:
  web:
    external: true
