version: '3'

services:
  front:
    image: ippolab/athena-frontend
    container_name: athena_front
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-frontend"
      - "traefik.frontend.rule=Host:athena.${HOSTNAME}"
      - "traefik.port=80"
    networks:
      - web
  nginx:
    image: nginx:1.15.9-alpine
    container_name: athena_nginx
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-nginx"
      - "traefik.frontend.rule=Host:api.athena.${HOSTNAME};PathPrefix:/static,PathPrefix:/media"
      - "traefik.port=80"
    networks:
      - web
  back:
    image: ippolab/athena-backend
    container_name: athena_back
    restart: always
    depends_on:
      - db
      - redis
      - rabbit
    env_file:
      - .env
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-backend"
      - "traefik.frontend.rule=Host:api.athena.${HOSTNAME}"
      - "traefik.port=8000"
    networks:
      - web
  flower:
    image: mher/flower
    container_name: athena_flower
    restart: always
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-flower"
      - "traefik.frontend.rule=Host:flower.athena.${HOSTNAME}"
      - "traefik.frontend.auth.basic.usersFile=/.htpasswd"
      - "traefik.port=8888"
    networks:
      - web
  celery:
    image: ippolab/athena-backend
    container_name: athena_celery
    restart: always
    depends_on:
      - db
      - redis
      - rabbit
    env_file:
      - .env
    command: celery worker -A athena --concurrency=4
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-celery"
      - "traefik.frontend.rule=Host:"
    networks:
      - web
  celery-beat:
    image: ippolab/athena-backend
    container_name: athena_celery_beat
    restart: always
    depends_on:
      - db
      - redis
      - rabbit
    env_file:
      - .env
    command: celery beat -A athena
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-celery-beat"
      - "traefik.frontend.rule=Host:"
    networks:
      - web
  db:
    image: postgres:11.2-alpine
    container_name: athena_postgre
    restart: always
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-postgre"
      - "traefik.frontend.rule=Host:"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - web
  redis:
    image: redis:5.0.3-alpine
    container_name: athena_redis
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-redis"
      - "traefik.frontend.rule=Host:"
    networks:
      - web
  adminer:
    image: adminer
    container_name: athena_adminer
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-adminer"
      - "traefik.frontend.auth.basic.usersFile=/.htpasswd"
      - "traefik.frontend.rule=Host:adminer.athena.${HOSTNAME}"
      - "traefik.port=8080"
    networks:
      - web
  rabbit:
    image: rabbitmq:3.7.13-management-alpine
    container_name: athena_rabbitmq
    hostname: rabbitmq
    restart: always
    env_file:
      - .env
    volumes:
      - ./rabbit-data:/var/lib/rabbitmq/
    labels:
      - "traefik.enable=true"
      - "traefik.backend=athena-rabbit"
      - "traefik.frontend.auth.basic.usersFile=/.htpasswd"
      - "traefik.frontend.rule=Host:rabbit.athena.${HOSTNAME}"
      - "traefik.port=15672"
    networks:
      - web

networks:
  web:
    external: true
